### ISSUE TITLE
rules_foreign_cc is failing with Bazel@HEAD in Downstream CI.

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_foreign_cc#1054]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3090#0188ad5a-7d51-468f-a6c5-9711ab308d0f

Platform:  Multiple

Logs:  
```
ERROR: /private/var/tmp/_bazel_buildkite/4e5225130fdc7fb54adecff717a61430/external/rules_python/docs/BUILD:36:12: no such target '@bazel_tools//tools/python:private/defs.bzl': target 'private/defs.bzl' not declared in package 'tools/python'

```

Steps:
```
git clone https://github.com/bazelbuild/rules_foreign_cc.git
git reset 62230f8a2123a64b411a3888f75128a10bfe0755 --hard
export USE_BAZEL_VERSION=06992d2d0da3ab4628028cecbb3f3dc4965f9e88
bazel build //...

```

CC @meteorcloudy

**Comment by meteorcloudy** [comment]
The missing bzl file was removed from Bazel HEAD at https://github.com/bazelbuild/bazel/commit/d7f248555f83d0f1825441e6c2a8be6e4bdcf985

**Comment by jsharpe** [comment]
This requires bumping rules_python which requires bumping the min supported version to 5.4.0. @UebelAndre @jheaff1 do you have any opinions on doing this now? 4.x goes out of support Jan 2024.

**Comment by jheaff1** [comment]
I think we’ve valiantly supported Bazel 4 up to this point but personally would have no qualms with bumping up to 5.4.0 given this issue

**Comment by jsharpe** [comment]
I'd propose we cut a release that is still compatible with 4.x as there's a fair amount of changes that have gone in since the last release and then we can land the bump to rules_python to fix the downstream CI and bump the min version up to 5.4.0. Sound reasonable?

**Comment by jheaff1** [comment]
> I'd propose we cut a release that is still compatible with 4.x as there's a fair amount of changes that have gone in since the last release and then we can land the bump to rules_python to fix the downstream CI and bump the min version up to 5.4.0. Sound reasonable?

I’d say that sounds very reasonable!

**Comment by sgowroji** [comment]
Gentle ping on this issue, Can anyone share the latest update. Thanks!

**Comment by sgowroji** [comment]
Hi Team, Any update on this issue?

**Comment by jsharpe** [comment]
Apologies; I have limited time available at the moment to sort out the releases to enable us to resolve this issue.

**Comment by jsharpe** [comment]
Looking at this some more - bumping rules_python only really bumps the min version for the examples build on CI. 4.x users can just set an older version of rules_python in their WORKSPACE file so I'm going to go ahead and bump rules_python so that the downstream CI is fixed.

**Comment by sgowroji** [comment]
Hi @jsharpe, CI is still failing https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3445#018bacb6-27ef-4fe2-8589-c2af863d1b94 . Can you take a look. Thanks!

**Comment by jsharpe** [comment]
Working towards this here: https://github.com/bazelbuild/rules_foreign_cc/pull/1127

**Comment by sgowroji** [comment]
We can close this issue now as the CI is failing with different error.
