### ISSUE TITLE
boost build fails

### ISSUE THREAD

**Issue by bbarnes52** [bazelbuild/rules_foreign_cc#81]
Attaching the output here as a file (it's quite long), I suspect this part is the error:
 
```
./boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory
```

[out.txt](https://github.com/bazelbuild/rules_foreign_cc/files/2359011/out.txt)

**Comment by bbarnes52** [comment]
that line does seem to be the error, the file /usr/include/python2.7/pyconfig.h simply does not exist in the filesystem. is having this available locally a prerequisite to building boost / should it be?

**Comment by bbarnes52** [comment]
Closing this, assuming that the correct solution is to just install python-dev.

**Comment by bbarnes52** [comment]
For posterity: you also need to install python-numpy.

I am getting `ERROR: /cloud/third_party/cmake/boost/BUILD:7:1: output 'third_party/cmake/boost/boost/lib/libboost_fiber.a' was not created`

Have not been able to determine what package needs to be installed to satisfy this requirement.

**Comment by irengrig** [comment]
Hi, sorry for the delay with the answer.
Apparently, Python should be provided in tools_deps attribute.
I wonder if just having the remote repository for Python and referencing it in this attribute would be enough.
Of course, also possible to install it with pip, but then it should be a rule similar to that building boost, with the corresponding shell script (and also pip should be installed).

**Comment by bbarnes52** [comment]
Thank you very much! For my understanding (and also for posterity), would you mind elaborating on which of the following issues are addressed by adding Python to the tools_deps attribute?

1. pyconfig.h not being found (I was able to resolve with `apt-get install python-dev`)
2. libboost_numpy.a not being created (I was able to resolve with `apt-get install python-numpy`) 
3. libboost_fiber.a not being created (have not found a workaround outside of forking repository and removing that line)

**Comment by irengrig** [comment]
Hi, I can not say that because I did not reproduce the situation, sorry.
1 is of course directly related to Python, while for 2 and 3 it is better to check the CMakeLists.txt for boost or the build output, usually some details are provided.

**Comment by bbarnes52** [comment]
Is it possible that you cannot reproduce because of local installs of required dependencies? I ask because I'm running inside a docker image built from ubuntu with only bazel and its dependencies installed. If there are certain dependencies (python-dev, python-numpy, etc) required to build boost, should those not be included explicitly as a dependency or at least documented?

**Comment by irengrig** [comment]
Yep, this is what I mean - I am building it in a sandbox, but certain standard paths where the tools are installed are still being checked (I mean the hardcoded paths in the external build scripts, like /usr/bin) and locally installed tools and dependencies can leak into this rule.

Of course, the more precise recipe for building boost we create, the better.
Currently I am working on some other part, with configure-make, can not say about the plans with improving the boost example or bringing Docker containers for testing. In general, I would like to have all that for this project.
You contribution is very welcome!

**Comment by blackliner** [comment]
Hi, `bazel build //cmake_pcl:pcl` still does not work out of the box, multiple warnings regarding a missing headerfile:
```
./boost/python/detail/wrap_python.hpp:50:11: fatal error: pyconfig.h: No such file or directory
 # include <pyconfig.h>
```
